
[[Anticorruption-Layer]]

==== [pattern]#Anticorruption Layer#



===== Intent

An anticorruption layer is a logical layer that provides a stable interface to (potentially) volatile software components. As long as this interface remains untouched developers can implement changes or even replace their own or third-party software without affecting the clients of this interface.

===== Description
The original definition <<Evans03,[Evans03, p. 365]>>:

[quote, Eric Evans, Domain Driven Design]
""
Create an isolating layer to provide clients with functionality in terms of their own domain model. The layer talks to the other system through its existing interface, requiring little or no modification to the other system. Internally, the layer translates in both directions as necessary between the two models.
""

===== Experiences 

Here are some real-life experiences:

* Anticorruption layer for a search-index to defer the decision if the best performance can be achieved with Elastic Search, Solr or a self-developed Lucene index.

===== Applicability

Apply this pattern when clients shall be protected from internal changes in a module or subsystem.

===== Consequences

* Allows to (ex)change software elements without affecting depending components
* Introduces one more level of indirection and thus may increase complexity

===== Also Known As

* Isolation layer


===== Related Patterns

* <<Isolate-Changes>>, as an alternative or complimenting approach
* Bulkhead (<<Nygard07>>, p. 119ff.), which can be placed between two systems to avoid the propagation of faults from one system to the other system.

===== References

* <<Evans03>> p. 364ff.

