[[Measure]]
==== [pattern]#Measure#

===== Intent

If you don’t measure it, you can’t optimize it. -- Coda Hale

===== Description

TODO: explain different kind of metrics (static-code, runtime, organisational...)

===== Experiences

===== Risks
If you measure too many different parameters or attributes, you might drown in numbers.


===== Applicability

This pattern should always be considered.

===== Consequences

===== Also Known As

* quantitative analysis
* quantitative runtime analysis
* profiling
* organisational metrics

===== Related Patterns

* This pattern is an important enabler for a successful <<Runtime-Artifact-Analysis>> or <<Performance Analysis>>.
* <<Instrument-System>> and <<Profiling>> are very similar to this pattern, however they are limited to a temporary instrumentation that is needed during the Analysis phase to identify or scope a certain problem that cannot be isolated without modifying the code. 

===== References

https://www.youtube.com/watch?v=czes-oa0yik
