:numbered!:

== About aim42

[role="lead"]
aim 42 supports software evolution, maintenance, migration and improvement - in a systematic and pragmatic way.



[NOTE]
--
http://aim42.org[aim42] is a collection of practices and patterns to support software evolution, modernization, maintenance, migration and improvement of software systems:

aim42:

. helps you optimize your software and reduce maintenance cost
. helps you to identify critical issues, technical debt and risks
. supports both business and technical stakeholders
. organizes patterns and practices in three phases (<<Analyze>>, <<Evaluate>> and <<Improve>>)
. Free and open-source, <<contributions,contributions>> welcome.
. Grounded in practice , proven approaches, backed by serious research.
--

Authored by the aim42 community, lead by Dr. Gernot Starke <gernot.starke@innoq.com>

//[small]#Version {version}, last update {docdate}, Status:#
image:https://img.shields.io/badge/Version-{version}-green.svg[{version}]
image:https://img.shields.io/badge/Date-{currentDate}-green.svg[/{currentDate}]
image:https://img.shields.io/travis/aim42/aim42/master.svg[link="https://travis-ci.org/aim42/aim42",window="_blank", alt="build-status:unknown"]
image:https://img.shields.io/github/issues/aim42/aim42.svg[link="https://github.com/aim42/aim42/issues",window="_blank", alt="nr-of-issues:unknown"]
image:https://img.shields.io/github/stars/aim42/aim42.svg[link="https://github.com/aim42/aim42",window="_blank", alt="github-stars"]
image:https://img.shields.io/github/contributors/aim42/aim42.svg[link="https://github.com/aim42/aim42",window="_blank", alt="github-contributors"]
image:https://img.shields.io/twitter/follow/gernotstarke.svg?style=social&label=Followers[link="https://twitter.com/gernotstarke",window="_blank", alt=""]
