:numbered:

[[Evaluate]]
== Evaluate

=== Goals

Make the issues, problems and risks found during the *analysis* comparable by
determining their *value* (that's why we call this activity *evaluate*):

. determine _value_ of problems, issues, risks and their remedies 
. prioritize issues, their remedies and improvement measures 


=== Pattern and Practices for Evaluation

* Determine Feature Value
* Determine Problem Cost
* Estimate Remedy Cost
* Failure Mode And Effect Analysis
* Impact Analysis
* Separate Cause From Effect


// the detailed description of the evaluation-patterns
[[Determine-Feature-Value]]
==== Determine Feature Value
Determine the (monetary) value of a given feature, so you can compare features of the system with each other.

* Involve business or management stakeholders, as they often have a clear notion of business value.
* If you cannot determine real numbers available, use <<Explicit-Assumption, explicit assumptions>> 
* Instead of numbers, you might use categories or orders-of-magnitude (like small, medium, large). Youo should prefer numbers, though!




[[Determine-Problem-Cost]]
==== Determine Problem Cost
Determine how much a given problem costs (in money or effort) in a period of time. 

For example, if a server needs to be rebooted once every 24hrs and an operator needs 30 minutes to perform this reboot (and corresponding activities) - then you can approximate the cost of this problem for, let's say, a month:

5 workdays * 4 weeks * 30 min = 10hrs of operator-effort.

If you multiply with (approximate or average) wage, you get _problem cost_.

* If you cannot determine real numbers available, use <<Explicit-Assumption, explicit assumptions>> 


==== Estimate Remedy Cost

See: "Software Estimation. The Black Art Demystified (Steve McConnell)"



