== Pattern index

This chapter contains an alphabetic list of all patterns, practices and methods with a
short description and links to the explanation.

. *<<Anticorruption-Layer>>*
+
Isolate clients from internal changes of suby-systems or modules. The original definition:
+

[quote, Eric Evans]
""    
Create an isolating layer to provide clients with functionality in terms of their own domain model. The layer talks to the other system through its existing interface, requiring little or no modification to the other system. Internally, the layer translates in both directions as necessary between the two models. (Domain Driven Design, page 365)
""
Category: <<Improve>>
+

. *<<ATAM>>*
+
Systematic approach to find architectural risks, tradeoffs (compromises) and sensitivity points.
Category: <<Analyze>>
+

. [[Architecture-Backlog]]
[pattern]#Architecture-Backlog#:: Keep a prioritized list of improvement tasks (_remedies_) with their
as a backlog, parallel to the (regular) feature backlog. 
Category: <<Improve>>
+

. [[Architecture-Documentation]]
[pattern]#Architecture Documentation#:: Document relevant structures, concepts, decisions, interfaces etc. of the system to increase. See <<arc42>> and <<View-Based-Understanding>>.
Category: <<Analyze>>
+

. [[Assertions]]
[pattern]#Assertions#:: Use assertions to verify preconditions and to make a program fail early when something goes fundamentally wrong.
Category: <<Improve>>
+

. [[Automated-Tests]]
[pattern]#Automated Tests#:: Introduce automated tests to verify correctness or runtime behavior. Unit-, integration-, acceptance-, load- or database-tests are well-known specialisations of this.
Category: <<Improve>>
+


. [[Branch-For-Improvement]]
[pattern]#Branch For Improvement#:: Introduce distinct branches in your version control system to reflect improvements.
Category: <<Improve>>
+

. *<<Capture-Quality-Requirements>>*
+
Part of <<ATAM>>, Capture and document specific quality requirements. Specialisation of <<Requirements-Analysis>>. 
Category: <<Analyze>>
+

. [[Change-by-Extension]]
[pattern]#Change by Extension#:: Enable efficient change by creating new components instead of modifying existing ones.
Category: <<Improve>>
+

. [[Change-by-Copy]]
[pattern]#Change by Copy#:: Isolate competing change necessity by copying and allowing the copies to evolve independently.
Category: <<Improve>>
+


. *<<collect-opportunities-for-improvement>>*
+
Keep a list of possible and potential measures, remedies, tactics, strategies for improvements. Regularly match those to your <<collect-problems, collection of problems>>.
Category: <<Crosscutting>>
+

. *<<collect-problems>>*
+
Keep a list of problems, issues and risks. Regularly match those to your <<collect-opportunities-for-improvement, collection of possible remedies>>.
Category: <<Crosscutting>> 


. *<<Context Analysis>>*
+
Analyse external interfaces for risk, technology, business value and other factors.
Category: <<Analyze>>
+


. *<<Data-Analysis>>*
+
Analyse and inspect the data created and manipulated by the system for its content, structure, quantity and size.
Category: <<Analyze>>
+ 


. *<<Debugging>>*
+
Identify the source of a bug or misbehavior by observing the
detailed flow of execution, e.g. stepwise execution of program statements. Usually supported by _debugger_. Specialisation of <<Root-Cause-Analysis>>.
Category: <<Analyze>>
+


. *<<Development Process Analysis>>*
+
Analyse and inspect the development process (as documented or described by stakeholders) for appropriateness, problems or problem-areas.
Category: <<Analyze>>
+

. *<<Documentation-Analysis>>*
+
Analyse existing documentation for availability, correctness, actuality, problems or problem-areas. 
Category: <<Analyze>>
+


. [[Document-Problems]] 
[pattern]#Document Problems#:: See <<improvement-backlog, Improvement Backlog>>.
Category: <<Crosscutting>>
+


. *<<Estimate-Feature-Value>>*
+
Estimate the (monetary) value of a given feature, so you can compare features of the system with each other.
Category: <<Evaluate>>
+

. *<<Estimate-In-Interval>>*
+
Estimation differs from *measurement* in its inherent uncertainty. Therefore, estimate in intervals, giving lower and upper bounds. The difference between the two shows your confidence in the estimate. Low (relative) difference means high confidence. 
Category: <<Evaluate>>
+

. *<<Estimate-Problem-Cost>>*
+
Estimate how much a given problem costs (in money or effort) in a period of time or a frequency. 
Category: <<Evaluate>>
+

. *<<Estimate-Remedy-Cost>>*
+
Determine how much a specific remedy (a set of actions taken to eliminate or reduce a specific problem or issue) is likely to cost (in money and/or effort).
Category: <<Evaluate>>
+

. *<<Expect-Denial>>*
Some people will oppose your findings, will whitewash or sugarcoat issues, problems or <<Root-Cause-Analysis, root causes>>. Regardless on how careful you prepared your analysis, they will try to diminish or attack your findings. Category: <<Crosscutting>>
+

. *<<Explicit-Assumption>>*
+
Compensate missing facts (especially requirements, goals, estimates, opinions) by explicit (usually written) assumptions about those facts.
Category: <<Crosscutting>>
+

. [[Extract-Reusable-Component]]
[pattern]#Extract Reusable Component#:: Extract code from an existing system to create a reusable component. See <<SERIOUS-Refactoring>>, page 95.
Category: <<Improve>>
+


. *<<Fail-Fast>>*
+
Identify quality issues as early as possible and aim to fix them.
Category: <<Crosscutting>>
+

. [[Failure-Mode-And-Effect-Analysis]]
[pattern]#Failure Mode And Effect Analysis#:: Systematically analyze postulated failures (problems, issues) and identify the resultant effects on overall system operations. 
Category: <<Evaluate>>
+

. *<<Fast-Feedback>>*
+
Evaluate the quality of work artifacts and processes as early as possible. Enables teams to apply corrective actions or take countermeasures as early as possible.
Category: <<Crosscutting>>
+

. [[Front-End-Switch]] 
[pattern]#Front End Switch#:: Route front-end requests to either new or old backend systems, depending on their nature.
Category: <<Improve>>
+

. [[Group-Improvement-Actions]]
[pattern]#Group Improvement Actions#:: Collect several improvement actions, which can or shall be applied or implemented together.
Category: <<Improve>>
+

. [[Handle-If-Else-Chains]]
[pattern]#Handle If Else Chains#:: Refactor nested if-then-else structures for improved understandability.
Category: <<Improve>>
+

. *<<Hierarchical-Quality-Model>>*
+
Decompose the overall goal of "high quality" into more detailed and precise requirements, finally resulting in a tree-like structure. See <<ATAM>> and <<Quality-Requirements>>.
Category: <<Analyze>>
+

. [[Impact-Analysis]]
[pattern]#Impact Analysis#:: Determine what impact (in code, concepts and the organization) a specific action (e.g. refactoring) will or might have.
Category: <<Evaluate>>
+

. [[Improve-Code-Layout]]
[pattern]#Improve Code Layout#:: Making code easier to read results in better understandability.
Category: <<Improve>>
+

. *<<Improve-Logging>>*
+
Making runtime analysis easier with meaningful logs. This includes decentralized log analysis as well as well-structured log levels, markers and log message phrasing.
Category: <<Improve>>
+

. *<<improvement-backlog>>*
+ 
Keep a backlog of possible improvements, remedies, tactics or strategies.
Category: <<Crosscutting>>
+


. *<<Instrument-System>>*
+
Instrument either the executable or the source code to make 
<<Explicit-Assumption, assumtions explicit>> and expand on <<Runtime-Analysis>> and 
<<Runtime-Artifact-Analysis>>. 
Category: <<Analyze>>
+

. *<<Interface-Segregation-Principle>>*
+
Reduce coupling between clients and service provider.
Category: <<Improve>>
+


. *<<Introduce-Boy-Scout-Rule>>*
+
Establish a policy to perform certain structural
implrovements each time an artifact (sourcecode, configuration, documents etc.)
is changed. Usable in situations where a <<Refactoring-Plan>> is not feasible or in
addition to such a plan.
Category: <<Improve>>
+

. [[Introduce-Layering]]
[pattern]#Introduce Layering#:: Introduce _layers_ within the source code to improve _separation of concern_. It's common to have at least a _business layer_ and an _interface layer_ - the latter for both user- and programatic interfaces. See http://blog.8thlight.com/uncle-bob/2012/08/13/the-clean-architecture.html[Uncle Bob's Clean Architecture] for a short summary.
Category: <<Improve>>
+

. [[Isolate-Changes]]
[pattern]#Isolate Changes#:: Introduce interfaces and intra-system borders, so that changes cannot propagate to other areas.
Category: <<Improve>>
+

. *<<Issue-Tracker-Analysis>>*
+
Analyse entries from issue-tracker to identify critical areas, components or stakeholders. 
Category: <<Analyze>>
+

. [[Keep-Data-Toss-Code]]
[pattern]#Keep Data Toss Code#:: A strategy to improve systems, keeping the data created with the (old) systems as foundation for a new one. Also described as <<Keller-Migration, Bridge-to-the-New-Town>> (by Wolfgang Keller). This is the opposite of <<Never-Change-Running-System>>.
Category: <<Improve>>
+

. [[Limit-Feature-by-Client]]
[pattern]#Limit Feature by Client#:: Support different feature sets for different clients, fade out legacy versions based on usage.
Category: <<Improve>>
+

. *<<Manage-Complex-Client-Dependencies-With-Facade>>*
+
Simplify the interaction of a client with a set of service components.
Category: <<Improve>>
+

// . *<<Measure-Everything>>*
. [[Measure-Everything]]
//+
Measure Everything:: Gather runtime metrics and make them visual on dashboards in order to make your system behavior more predictable and assumed coincidences explainable. Examples of such metrics are thread pool saturation, number of failed logins, requests per second but also number of successful orders today.
Category: <<Improve>>
+

. [[Migrate-Data]]
[pattern]#Migrate Data#:: Transform existing data from one structure or representation into another by keeping its original intent or semantic intact.
Category: <<Improve>>
+

. [[Mikado-Method]]
[pattern]#Mikado-Method#:: Coordinated <<Refactoring, refactoring>> effort, described in the <<Mikado, Mikado-book>>.
Category: <<Improve>>


. [[Natural-Death]]
[pattern]#Natural Death#:: Keep old system running and only retire it once all objects contained reach end of life according to their life cycle. 
Category: <<Improve>>
+

. [[Never-Change-Running-System]]
[pattern]#Never Change Running System#:: To minimize risks, you should try to refrain from changes to existing (working) code - as every change
inevitably introduces new risks or even bugs.
Category: <<Improve>>
+

. [[Never-Rewrite-Running-System]]
[pattern]#Never Rewrite Running System#:: Joel Spolsky arguments, <<Spolsky-NeverRewrite, never to rewrite a system from scratch>>, as you will likely make many new mistake and won't generate much added value.
Category: <<Improve>>
+

. *<<Organizational-Analysis>>*
+
Analyse and inspect organization(s) responsible for the system.
Category: <<Analyze>>
+

. [[Outside-in-Interfaces]]
[pattern]#Outside-in Interfaces#:: Modularize system in line with external, modular interfaces.
Category: <<Improve>>
+


. *<<Pre-Interview-Questionnaire>>*
+
Prior to interviewing stakeholders, present them with a written questionnaire, so they can reflect in advance. A specialisation of <<Questionnaire>>.
Category: <<Analyze>>
+


. *<<Qualitative-Analysis>>*
+
Analyze which quality goals of the <<SuD>> are at risk and which are met by the current implementation. Needs concrete <<Quality-Requirements>>. See <<Atam>>
Category: <<Analyze>>
+

. [[Quality-Driven-Software-Architecture]]
[pattern]#Quality Driven Software Architecture# (QDSA):: Derive (technical, structural or process-related) decisions based upon detailed quality requirements. QDSA requires <<Capture-Quality-Requirements, explicit quality requirements>>. See <<Quality-Function-Deployment>>.
Category: <<Improve>>
+


. *<<Quantitative-Analysis>>*
+
Measure artifacts or processes within the system, e.g. source code. For example, see <<Runtime-Analysis>> and <<Static-Code-Analysis>>.
Category: <<Analyze>>
+

. *<<Questionnaire>>*
+
Written collection of questions presented to stakeholders. Can be addendum, preparation or replacement of <<Stakeholder-Interview>>.
Category: <<Analyze>>
+

. [[Refactoring]]
[pattern]#Refactoring#:: Source code transformation that does not change functionality of system. See <<Fowler-Refactoring>>.
Category: <<Improve>>
+

. [[Refactoring-Plan]]
[pattern]#Refactoring Plan#:: The route of refactoring, as discussed within the development team. This plan should always be visible to every team member.
Category: <<Improve>>
+

. *<<Requirements-Analysis>>*
+
Analyze and document (current) requirements: required features and required constraints
Category: <<Analyze>>
+

. [[Remove-Nested-Control-Structures]]
[pattern]#Remove Nested Control Structures#:: Re-structure code so that deeply nested or complicated control structures are replaced by semantically identical versions. Special case of <<Refactoring>>, similar to <<Untangle-Code>>.
Category: <<Improve>>
+

. *<<Root-Cause-Analysis>>*
+
_Find the evil at the bottom_: Explicitely differentiate between symptom and cause: Identify root causes of symptoms, problems or issues.
Category: <<Analyze>>
+

. *<<Runtime-Analysis>>*
+
Analyze the runtime behavior of the <<SuD>>, e.g. with respect to time and resource consumption or creation. See <<Profiling>>, <<Performance-Analysis>> and <<Runtime-Artifact-Analysis>>.
Category: <<Analyze>>
+

. [[Sample-For-Improvement]]
[pattern]#Sample For Improvement#:: Provide concrete code example for typical improvement situations, so that developers can improve existing code easily.
Category: <<Improve>>
+

. [[Schedule-Work]]
[pattern]#Schedule Work#:: Schedule refactoring or improvement work, so that all (business and technical) stakeholders know about them. 
Category: <<Improve>>
+


. *<<Separate-Cause-From-Effect>>*
+
See <<Root-Cause-Analysis>>.
Category: <<Crosscutting>>
+

. *<<Software-Archeology>>*
+
Understand software by analysing its source code, usually in absence of other documentation or knowledge sources.  
Category: <<Analyze>>
+

. *<<Stakeholder-Analysis>>*
+
Find out which people, roles, organizational units or organizations have interests in the <<SuD>>.
Category: <<Analyze>>
+


. *<<Stakeholder-Interview>>*
+
Conduct personal interviews with key persons of the <<SuD>> or associated processes to identify, clarify or discuss potential issues and remedies.
Category: <<Analyze>>
+

. [[Stakeholder-Specific-Communication]]
[pattern]#Stakeholder Specific Communication#:: Communicate with stakeholders by actively applying their specific or favored terminology and/or communication channels.
Category: <<Crosscutting>>
+


. *<<Static-Code-Analysis>>*
+
Analyse source code to identify building blocks and their dependencies, determine complexity, coupling, cohesion and other structural properties.
Category: <<Analyze>>
+

. [[Structural-Analysis]]
[pattern]#Structural Analysis#:: Analyze the static structures (e.g. building block structure) of the <<SuD>>, e.g. package or module dependencies, runtime- and/or deployment dependencies. See the more specific <<Static-Code-Analysis>>, <<Context-Analysis>> and <<Data-Analysis>>. 
Category: <<Analyze>>
+

. *<<Systematic-Decisions>>*
+
Systematically prepare and take decisions by finding appropriate options, check assumptions, overcome emotion and prepare to be wrong. See <<heath-decisive, Decisive (by C+D Heath)>>.
Category: <<Crosscutting>>
 

. *<<Take-What-They-Mean>>*
+
Natural language has the risk, that semantics on the senders' side differs from semantics of the receiver: People simply misunderstand each other because _meaning_ of words differ between people. Pattern provided by Phillip Ghadir (who is too humble to claim this discovery)
Category: <<Analyze>>
+

. [[Toggle-Feature]]
[pattern]#Toggle Feature#:: Simultaneously support evolved, competing or conflicting features at runtime by toggling feature flags.
Category: <<Improve>>
+

. *<<Traceability>>*
+
Maintain references to the origin of problems or issues: Remember who told you about a problem, in which documents you found issues and in what version of the source you identified risks or faults. 
Category: <<Crosscutting>>
+


. [[Untangle-Code]]
[pattern]#Untangle Code#:: Remove unneccessary complications in code, e.g. nested structures, dependencies, dead-code, duplicate-code etc. See <<Remove-Nested-Control-Structures>>. Special case of <<Refactoring>>.
Category: <<Improve>>
+


. [[Use-Case-Cluster]]
[pattern]#Use Case Cluster#:: Understand system functionality by grouping functionality into clusters to reduce complexity.
Category: <<Analyze>>
+

. *<<Use-Invariants-To-Kill-Zombies>>*
+
Use Invariants to make sure that you can
kill Zombies safely. If code seems to be ``dead'' -- meaning that it
supposedly isn't called anymore -- but no one dares to remove it from the
codebase, the introduction of invariants can provide reliable feedback on
whether it is safe to remove the code or not.
Category: <<Improve>>
+

. *<<View-Based-Understanding>>*
+
Create architectural views (mainly building block view) to understand and communicate code structure.
Category: <<Analyze>>
+

