[[contributions]]

=== Contribute to aim42.org icon:smile-o[]
This content is open source! The source is hosted under the aim42 organization on GitHub.

If you want to help by improving upon it, fork the project, revise the content, then send a pull request. 

icon:github[2x] Source:: 
aim42 currently provides a _method guide_, the asciidoc sources are hosted at https://github.com/aim42/aim42[GitHub under the aim42 organization].

icon:bolt[2x] Issues:: 
Look over https://github.com/aim42/aim42/issues[our open issues], pick one, fork the repository and resolve the issue. Send over a pull request!

icon:twitter[2x] Twitter:: 
https://twitter.com/arc_improve42[@arc_improve42]

icon:inbox[2x] Mailing list::
There's even a (human-managed) mailing list: If you like to participate, send your subscribe-request to aim42-at-lists.innoq.com. 

icon:comment-o[2x] Suggestions::
In case you have ideas, critique or proposals - just let us know at aim42-at-lists.innoq.com.

[small]#(due to increased spam we had to remove the convenient mailto links, sorry)#

