
=== The Team

For a current and complete overview, please see the https://github.com/aim42/aim42/graphs/contributors[contributor page]
on Github.

* Gernot Starke (innoQ Fellow, project founder): setup, patterns, practices, maintenance.
* Alex Heusingfeld (innoQ): hero-of-the-build, Travis-CI integration, numerous discussions.
Started the idea of a distinct _user guide_...
* Peter Hruschka (Atlantic Systems Guild): reviews + comments,
  especially to the intricacies of the <<Domain-Model>>.
* Christine Koppelt (innoQ): improvement-patterns
* Michael Mahlberg (Consulting Guild): patterns and practices.
* Burkhard Neppert (innoQ): review, method
* Roland Schimmack: review, practices and patterns, bugfixes
* Oliver Tigges (innoQ): patterns and practices
* Stefan Tilkov (innoQ): maintenance and evolution patterns.
* Tammo van Lessen (innoQ): improvement patterns, technical debt contribution
* Sven Johann (innoQ): several improvements on various patterns
* Matthias Möser (Kassenärztliche Vereinigung Bayerns): improvement patterns, rewrite
* (what are you waiting for - *join us*!)


Comments and suggestions by Markus Harrer, Phillip Ghadir - and numerous (anonymous) project-teams from all around the IT-world.
