[[Report-Structure]]
=== [pattern]#Report-Structure# 

When you examine (audit, review) systems, as proposed
in <<Analyze>>, you often need to prepare a report for
the management in charge.

This practice proposes a generic report structure you
might use in preparing such documents. 

[options="header", cols="1,4"]
.Report Structure
|===
| Chapter | Description 

| Formalities  | formal stuff, like disclaimer, references to
                 contractual documents, table of contents,
                 licence, change history etc.

| Management Summary | 1, at most 2 page summary 

| Goals | describe the goals of the review/audit.

| Review Approach | brief description how the review was conducted,
                    outline the activities or actions performed.
| Stakeholders     | outline which stakeholders participated, 
                     in what form, at that time  
| Findings         | in order of importance or priority, list
                     and explain your findings
| Proposed Actions |
| Conclusion       |
| Appendix: Sources | list your sources and references, e.g. documents, 
                         source-code, interview protocols, 
                         issue-trackers, websites etc.
| Appendix: The Team | briefly introduce the review team and explain 
                       their role in the review.


|===



==== Related Practices

* <<Slide-Or-Write>> to decide, wether you really need to prepare a written report.

* <<Traceability>>, to ensure you have proper sources for all important issues.
