[[Slide-Or-Write]]
=== [pattern]#Slide or Write# 

In every review you will face the question of how to deliver and present the results to the customer. Will you write a long and formal report document or is a set of presentation slides adequate and sufficient?

==== Intent

* Consider format and structure of the review report early.
* Ensure that you share a common vision with your customer about the preparation of results .
* Remind contractual agreements and formal requirements, especially if someone might take offence by your report.

==== Description

There are two common ways to deliver review results:

* As a formal document (Word, PDF, etc.)
* As a collection of slides (PowerPoint, Keynote, etc.) and a presentation

In general it is recommended to write the review results down in a well-structured document. This form is suitable to contain a lot of details and background information, so that it is easy e.g. to trace back a recommendation to a stakeholder interview. A written document can (and should) contain all information needed to understand the review starting position, targets, approach and findings, without spoken words and additional explanations. If the results shall supplementary be presented to some audiences it is easy to create purposeful slides from this document.

A set of PowerPoint slides as only result is adequate if the customer has been closely involved in the review process and is mainly interested in the outcome and if there will definitely be a presentation given to all relevant stakeholders. In this case the creation of slides with the most important bullet points might be quicker than the writing of detailed, well formulated text.

==== Experiences

In a review for a financial broker we agreed initially to deliver a detailed document with the results. When we were later asked to present the outcomes to two different audiences (engineers and management) it was quite easy to create specific slides for both of them from the ~ 40 pages of documentation.

In another case we planned to present out review finding in one big meeting and so we wrapped all findings into briefly and concise slides. Later some executives who missed the meeting complained that they needed some spoken explanations to understand the presentation document. We spent much more time in subsequently writing out the background information as if we had worked on a result document from beginning on.


==== Related Patterns

* <<Report-Structure>>
* <<Traceability>>
