[[Qualitative-Analysis]]
=== Qualitative Analysis 

==== Intent

Find out (analyze):


* wether quality requirements can be met by the system, 
* which specific quality requirements are risks with respect to the current architecture,
* which specific quality requirements are currently non-risks 


==== Description

. <<Capture-Quality-Requirements, Capture quality requirements>> to ensure you have explicit, specific, valid and current _quality requirements_ available - preferably in form of _scenarios_.
. Prioritize these scenarios with respect to business value or importance for the authoritative stakeholders.
. For every important scenario: 
.. analyze the architectural approach the system takes,
.. decide wether this approach seems appropriate or risky   

==== Experiences

* Conducting workshops with a variety of stakeohlders often leads to intense and productive communication.

==== Applicability

Use qualitative analysis to support in the following situations:

* You need to analyze which specific quality requirements are at risk and which will most likely be met by the system.

* You have a variety of different stakeholders or groups which can all impose quality requiements - but have not yet agreed on a common set of such requirements.

* A current and understandable collection of specific quality requirements for the system is missing.

==== Consequences


==== Also Known As
* <<ATAM, Architecture Tradeoff Analysis>>

==== Related Patterns


==== References

* ATAM - Architecture Tradeoff Analysis Method. Published by the Software Engineering Institute in numerous whitepapers and books, especially <<Clements-ATAM>>.
 
