[[Take-What-They-Mean]]
=== Take What They Mean, Not What They Say 

==== Intent
Find out the real meaning/intention of stakeholders


==== Description
Natural language has the risk that semantics on the senders' side differs from semantics of the receiver: People simply misunderstand each other because _meaning_ of words differs between people. 

Therefore: what people mean/want/need is sometimes not what they say. This is due either to semantic differences on sender and receive sides, or to other reasons.

NLP (neurolingustic programming) practitioners recommend to _mirror_ things you hear to your communication partners in your own words. This might facilitate understanding.


==== Applicability
Apply this pattern whenever you communicate to other people (aka stakeholders).


==== Consequences
* Improved understanding between stakeholders.
* <<Explicit-Assumption, Explicit assumptions>>, instead of implicit ones.


==== Related Patterns
* In every <<Stakeholder-Interview>> you should apply this pattern. 
* <<Stakeholder-Analysis>> to find out, who are the important stakeholders you should apply this pattern to.

==== References
Special thanx to Phillip Ghadir (who is too humble to claim this discovery) for giving this pattern its name. 

